# Generated by Django 3.2.8 on 2021-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_info', models.TextField(max_length=300)),
                ('product_photo_1', models.ImageField(upload_to='Product/%Y/%M/')),
                ('product_photo_2', models.ImageField(upload_to='Product/%Y/%M/')),
                ('product_photo_3', models.ImageField(upload_to='Product/%Y/%M/')),
                ('product_photo_4', models.ImageField(upload_to='Product/%Y/%M/')),
                ('product_size_id', models.ManyToManyField(to='website.Product_size')),
            ],
        ),
    ]
